export const metadata = {
  title: 'pokemon memeory cards',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      {children}
    </html>
  )
}
